"""Protocol interfaces for core↔EE boundary type safety.

Defines ``@runtime_checkable`` Protocol classes so that mypy catches
contract mismatches at static analysis time.  The null implementations
in ``core/observability_protocol.py`` and the real implementations in
``observability/`` both satisfy these protocols.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class MetricsCollectorProtocol(Protocol):
    """Contract for Prometheus metrics collection."""

    enabled: bool

    def record_llm_call(self, **kw: Any) -> None: ...
    def record_cache_hit(self, **kw: Any) -> None: ...
    def record_cache_miss(self, **kw: Any) -> None: ...
    def record_pii_detection(self, **kw: Any) -> None: ...
    def record_budget_violation(self, **kw: Any) -> None: ...
    def record_local_routing(self, **kw: Any) -> None: ...
    def record_kill_switch_block(self, **kw: Any) -> None: ...
    def record_blast_radius_pause(self, **kw: Any) -> None: ...
    def record_rate_limit(self, **kw: Any) -> None: ...
    def record_circuit_breaker(self, **kw: Any) -> None: ...
    def set_active_sessions(self, count: int) -> None: ...
    def generate_metrics(self) -> str: ...


@runtime_checkable
class AlertManagerProtocol(Protocol):
    """Contract for webhook-based alerting."""

    def fire(self, event_type: str, payload: dict[str, Any]) -> None: ...


@runtime_checkable
class TimeSeriesAggregatorProtocol(Protocol):
    """Contract for time-series observability data."""

    def get_timeseries(self, *args: Any, **kw: Any) -> dict[str, Any]: ...
    def get_latency(self, *args: Any, **kw: Any) -> dict[str, Any]: ...
    def get_breakdown(self, *args: Any, **kw: Any) -> dict[str, Any]: ...
