"""Middleware protocol and context for StateLoom pipeline."""

from __future__ import annotations

from collections.abc import Awaitable, Callable
from dataclasses import dataclass, field
from typing import Any, Protocol, runtime_checkable

from stateloom.core.config import StateLoomConfig
from stateloom.core.event import Event
from stateloom.core.session import Session


@dataclass
class StreamChunkInfo:
    """Provider-agnostic metadata extracted from a single stream chunk.

    Attributes:
        text_delta: Incremental text content from this chunk.
        finish_reason: Non-None on the final chunk (e.g. ``"stop"``).
        tool_call_delta: Partial tool-call payload, if this chunk carries one.
        prompt_tokens: Prompt token count (only set when ``has_usage`` is True).
        completion_tokens: Completion token count (only when ``has_usage``).
        has_usage: True if this chunk includes a ``usage`` object (typically
            the last chunk in an OpenAI stream).
    """

    text_delta: str = ""
    finish_reason: str | None = None
    tool_call_delta: dict[str, Any] | None = None
    prompt_tokens: int = 0
    completion_tokens: int = 0
    has_usage: bool = False


@dataclass
class MiddlewareContext:
    """Mutable context threaded through every middleware in the pipeline.

    Created once per LLM call.  Pre-call middleware populates control flags
    and events; the terminal node executes the actual LLM call (unless
    ``skip_call`` is True); post-call middleware reads the response and
    records events.

    Field groups:

    - **Identity**: ``session``, ``config``, ``provider``, ``method``, ``model``
    - **Request**: ``request_kwargs``, ``request_hash``, ``provider_base_url``
    - **Response** (populated after call): ``response``, token counts, ``latency_ms``
    - **Control**: ``skip_call``/``cached_response``, ``auto_route_eligible``
    - **Events**: ``events`` list, appended to by middleware
    - **Streaming**: ``is_streaming``, ``_on_stream_complete`` callbacks
    - **Internal**: ``_precomputed_complexity_score``, ``_embedding_cache``
    """

    # Session this call belongs to
    session: Session

    # Config
    config: StateLoomConfig

    # The LLM call details
    provider: str = ""  # Provider enum value or custom string
    method: str = ""  # "chat.completions.create"
    model: str = ""
    request_kwargs: dict[str, Any] = field(default_factory=dict)

    # Populated after the LLM call
    response: Any = None
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    latency_ms: float = 0.0
    is_streaming: bool = False
    request_hash: str = ""
    provider_base_url: str = ""  # Provider API endpoint URL (for compliance checks)

    # Events generated by middleware during this call
    events: list[Event] = field(default_factory=list)

    # Control flags — when skip_call is True the terminal node returns
    # cached_response instead of calling the LLM.  Both must be set together.
    skip_call: bool = False
    cached_response: Any = None

    # Only True for stateloom.chat() calls where no explicit model was given,
    # so the auto-router is allowed to reroute to a local model.
    auto_route_eligible: bool = False

    # Pre-computed complexity score set by PrecomputeMiddleware so that
    # AutoRouterMiddleware can skip redundant classification.
    _precomputed_complexity_score: float | None = field(default=None, repr=False, init=False)
    _precomputed_complexity_future: Any = field(default=None, repr=False, init=False)

    # Shared embedding cache (avoids recomputing embeddings across middleware)
    _embedding_cache: dict[str, Any] = field(default_factory=dict, repr=False, init=False)

    # Streaming callbacks — post-call middleware registers lambdas here
    # instead of running inline.  The stream wrapper fires them after the
    # generator is fully consumed.
    _on_stream_complete: list[Callable[[], None]] = field(
        default_factory=list, repr=False, init=False
    )
    # Set by the stream wrapper if the stream errors mid-iteration
    _stream_error: BaseException | None = field(default=None, repr=False, init=False)

    # Set by stream wrapper with serialized chunks for durable caching;
    # read by CostTracker to persist into the event's cached_response_json.
    _durable_cached_json: str | None = field(default=None, repr=False, init=False)

    # Framework-specific metadata (e.g., LangChain run_id, tags, chain name).
    # Keyed by framework name: {"langchain": {...}, "langgraph": {...}}.
    # Populated by Pipeline from the ContextVar; flowed into event.metadata by CostTracker.
    _framework_context: dict[str, Any] = field(
        default_factory=dict, repr=False, init=False
    )


@runtime_checkable
class Middleware(Protocol):
    """Protocol for a middleware in the StateLoom pipeline.

    Each middleware processes the context and calls call_next to continue
    the chain. Middleware can modify the context before/after the call.
    """

    async def process(
        self,
        ctx: MiddlewareContext,
        call_next: Callable[[MiddlewareContext], Awaitable[Any]],
    ) -> Any:
        """Process the context and delegate to the next middleware.

        Args:
            ctx: The mutable pipeline context for this LLM call.
            call_next: Async callable that invokes the next middleware (or
                the terminal LLM call).  Middleware must call
                ``await call_next(ctx)`` to continue the chain; skipping
                the call short-circuits downstream middleware.

        Returns:
            The LLM response (or cached response), propagated back through
            the chain.  Post-call logic runs after ``await call_next(ctx)``
            returns.
        """
        ...
