"""Event recorder middleware — persists events to the store."""

from __future__ import annotations

import logging
from collections.abc import Awaitable, Callable
from typing import TYPE_CHECKING, Any

from stateloom.middleware.base import MiddlewareContext
from stateloom.store.base import Store

if TYPE_CHECKING:
    from stateloom.core.interfaces import AlertManagerProtocol, MetricsCollectorProtocol

logger = logging.getLogger("stateloom.middleware.event_recorder")


class EventRecorder:
    """Persists events generated by other middleware to the store."""

    # Callback slots set by EE during registration.
    # When set, these replace the deferred-import paths.
    broadcast_fn: Any = None  # async callable(event_data_dict) | None
    audit_hash_fn: Any = None  # callable(audit_event, salt) -> str | None

    def __init__(
        self,
        store: Store,
        metrics: MetricsCollectorProtocol | None = None,
        alert_manager: AlertManagerProtocol | None = None,
    ) -> None:
        self._store = store
        self._metrics = metrics
        self._alert_manager = alert_manager

    async def process(
        self,
        ctx: MiddlewareContext,
        call_next: Callable[[MiddlewareContext], Awaitable[Any]],
    ) -> Any:
        try:
            result = await call_next(ctx)
        except Exception:
            # Persist any events accumulated before the exception (e.g.
            # budget_enforcement events appended before StateLoomBudgetError).
            if ctx.events:
                try:
                    await self._persist_events_async(ctx)
                except Exception:
                    logger.debug("Failed to persist events on exception path", exc_info=True)
            raise

        if ctx.is_streaming:
            ctx._on_stream_complete.append(lambda: self._persist_events(ctx))
        else:
            await self._persist_events_async(ctx)

        return result

    async def _persist_events_async(self, ctx: MiddlewareContext) -> None:
        """Async persistence path (original behavior for non-streaming)."""
        # HIPAA zero-retention: strip sensitive data before persistence
        if ctx.session.metadata.get("_compliance_zero_retention"):
            self._strip_sensitive_data(ctx)

        # Atomically save events + session when the store supports it
        if hasattr(self._store, "save_session_with_events"):
            try:
                self._store.save_session_with_events(ctx.session, list(ctx.events))
                self._record_metrics(ctx)
                self._fire_alerts(ctx)
                await self._broadcast_events(ctx)
                return
            except Exception as e:
                logger.warning(f"[StateLoom] Atomic save failed, falling back: {e}")

        # Fallback: save individually for custom Store implementations
        for event in ctx.events:
            try:
                self._store.save_event(event)
            except Exception as e:
                logger.warning(f"[StateLoom] Failed to save event: {e}")

        try:
            self._store.save_session(ctx.session)
        except Exception as e:
            logger.warning(f"[StateLoom] Failed to save session: {e}")

        self._record_metrics(ctx)
        self._fire_alerts(ctx)
        await self._broadcast_events(ctx)

    def _persist_events(self, ctx: MiddlewareContext) -> None:
        """Sync persistence path for streaming callbacks."""
        import threading

        # HIPAA zero-retention: strip sensitive data before persistence
        if ctx.session.metadata.get("_compliance_zero_retention"):
            self._strip_sensitive_data(ctx)

        # Atomically save events + session when the store supports it
        if hasattr(self._store, "save_session_with_events"):
            try:
                self._store.save_session_with_events(ctx.session, list(ctx.events))
                self._record_metrics(ctx)
                self._fire_alerts(ctx)
                # Launch async broadcast in daemon thread
                threading.Thread(
                    target=self._broadcast_events_sync, args=(ctx,), daemon=True
                ).start()
                return
            except Exception as e:
                logger.warning(f"[StateLoom] Atomic save failed, falling back: {e}")

        for event in ctx.events:
            try:
                self._store.save_event(event)
            except Exception as e:
                logger.warning(f"[StateLoom] Failed to save event: {e}")

        try:
            self._store.save_session(ctx.session)
        except Exception as e:
            logger.warning(f"[StateLoom] Failed to save session: {e}")

        self._record_metrics(ctx)
        self._fire_alerts(ctx)
        threading.Thread(target=self._broadcast_events_sync, args=(ctx,), daemon=True).start()

    @staticmethod
    def _broadcast_events_sync(ctx: MiddlewareContext) -> None:
        """Run async broadcast from a sync context (daemon thread)."""
        import asyncio

        try:
            asyncio.run(EventRecorder._broadcast_events(ctx))
        except Exception:
            logger.debug("Failed to broadcast events from streaming callback", exc_info=True)

    def _strip_sensitive_data(self, ctx: MiddlewareContext) -> None:
        """Strip cached response bodies and shadow previews for zero-retention compliance."""
        from stateloom.core.event import LLMCallEvent, ShadowDraftEvent

        stripped = False
        for event in ctx.events:
            if isinstance(event, LLMCallEvent) and event.cached_response_json is not None:
                event.cached_response_json = None
                stripped = True
            elif isinstance(event, ShadowDraftEvent):
                if event.cloud_preview or event.local_preview:
                    event.cloud_preview = ""
                    event.local_preview = ""
                    stripped = True

        if stripped:
            # Emit audit event for the purge
            try:
                # Use callback if set by EE, otherwise fall back to import
                compute_audit_hash = EventRecorder.audit_hash_fn
                if compute_audit_hash is None:
                    from stateloom.compliance.audit import compute_audit_hash
                from stateloom.compliance.legal_rules import get_legal_rule
                from stateloom.core.event import ComplianceAuditEvent

                standard = ctx.session.metadata.get("_compliance_standard", "hipaa")
                audit_salt = ctx.session.metadata.get("_compliance_audit_salt", "")
                audit = ComplianceAuditEvent(
                    session_id=ctx.session.id,
                    step=ctx.session.step_counter,
                    compliance_standard=standard,
                    action="data_purged",
                    legal_rule=get_legal_rule(standard, "data_purged"),
                    justification=(
                        f"Response payloads and shadow previews stripped "
                        f"per {standard.upper()} zero-retention policy"
                    ),
                    target_type="session",
                    target_id=ctx.session.id,
                    org_id=ctx.session.org_id,
                    team_id=ctx.session.team_id,
                )
                audit.integrity_hash = compute_audit_hash(audit, audit_salt)
                ctx.events.append(audit)
            except Exception:
                logger.debug("Failed to create data_purged audit event", exc_info=True)

            # Warn if durable + zero-retention (compliance > convenience)
            if ctx.session.durable:
                logger.warning(
                    "Session '%s': durable mode with zero-retention — "
                    "cached responses stripped, durable resumption will re-execute all calls",
                    ctx.session.id,
                )

    def _record_metrics(self, ctx: MiddlewareContext) -> None:
        """Record Prometheus metrics from context events (fail-open)."""
        if self._metrics is None or not self._metrics.enabled:
            return
        try:
            from stateloom.core.event import (
                BudgetEnforcementEvent,
                CacheHitEvent,
                LLMCallEvent,
                LocalRoutingEvent,
                PIIDetectionEvent,
            )

            org_id = ctx.session.org_id or ""
            team_id = ctx.session.team_id or ""

            for event in ctx.events:
                if isinstance(event, LLMCallEvent):
                    self._metrics.record_llm_call(
                        model=event.model,
                        provider=event.provider,
                        latency_ms=event.latency_ms,
                        prompt_tokens=event.prompt_tokens,
                        completion_tokens=event.completion_tokens,
                        cost=event.cost,
                        org_id=org_id,
                        team_id=team_id,
                    )
                elif isinstance(event, CacheHitEvent):
                    self._metrics.record_cache_hit(
                        match_type=event.match_type,
                        org_id=org_id,
                        team_id=team_id,
                    )
                elif isinstance(event, PIIDetectionEvent):
                    self._metrics.record_pii_detection(
                        pii_type=event.pii_type,
                        action=event.action_taken,
                        org_id=org_id,
                        team_id=team_id,
                    )
                elif isinstance(event, BudgetEnforcementEvent):
                    self._metrics.record_budget_violation(
                        org_id=org_id,
                        team_id=team_id,
                    )
                elif isinstance(event, LocalRoutingEvent):
                    decision = "local" if event.routing_success else "cloud"
                    self._metrics.record_local_routing(
                        decision=decision,
                        org_id=org_id,
                        team_id=team_id,
                    )
        except Exception:
            logger.debug("Failed to record Prometheus metrics", exc_info=True)

    def _fire_alerts(self, ctx: MiddlewareContext) -> None:
        """Fire webhook alerts for notable events (fail-open)."""
        if self._alert_manager is None:
            return
        try:
            from stateloom.core.event import (
                BlastRadiusEvent,
                BudgetEnforcementEvent,
                CircuitBreakerEvent,
                KillSwitchEvent,
                RateLimitEvent,
            )

            for event in ctx.events:
                if isinstance(event, CircuitBreakerEvent) and event.state == "open":
                    self._alert_manager.fire(
                        "circuit_breaker_tripped",
                        {
                            "session_id": event.session_id,
                            "provider": event.provider,
                            "failure_count": event.failure_count,
                            "fallback_model": event.fallback_model,
                        },
                    )
                elif isinstance(event, BudgetEnforcementEvent):
                    self._alert_manager.fire(
                        "budget_exceeded",
                        {
                            "session_id": event.session_id,
                            "spent": event.spent,
                            "limit": event.limit,
                            "action": event.action,
                        },
                    )
                elif isinstance(event, KillSwitchEvent):
                    self._alert_manager.fire(
                        "kill_switch_activated",
                        {
                            "session_id": event.session_id,
                            "blocked_model": event.blocked_model,
                            "blocked_provider": event.blocked_provider,
                            "reason": event.reason,
                            "message": event.message,
                            "matched_rule": event.matched_rule,
                        },
                    )
                elif isinstance(event, RateLimitEvent) and event.rejected:
                    self._alert_manager.fire(
                        "rate_limit_rejected",
                        {
                            "session_id": event.session_id,
                            "team_id": event.team_id,
                        },
                    )
                elif isinstance(event, RateLimitEvent) and event.timed_out:
                    self._alert_manager.fire(
                        "rate_limit_timeout",
                        {
                            "session_id": event.session_id,
                            "team_id": event.team_id,
                            "wait_ms": event.wait_ms,
                        },
                    )
                elif isinstance(event, BlastRadiusEvent):
                    self._alert_manager.fire(
                        "blast_radius_pause",
                        {
                            "session_id": event.session_id,
                            "trigger": event.trigger,
                            "agent_id": getattr(event, "agent_id", ""),
                        },
                    )
        except Exception:
            logger.debug("Failed to fire alerts", exc_info=True)

    @staticmethod
    async def _broadcast_events(ctx: MiddlewareContext) -> None:
        """Broadcast events to connected WebSocket clients (fail-open)."""
        try:
            # Use callback if set by EE, otherwise fall back to import
            broadcast_event = EventRecorder.broadcast_fn
            if broadcast_event is None:
                from stateloom.dashboard.ws import broadcast_event

            for event in ctx.events:
                event_data: dict[str, Any] = {
                    "event_type": event.event_type.value
                    if hasattr(event.event_type, "value")
                    else str(event.event_type),
                    "session_id": event.session_id,
                    "timestamp": event.timestamp.isoformat()
                    if hasattr(event.timestamp, "isoformat")
                    else str(event.timestamp),
                }
                # Copy known event attributes
                for attr in (
                    "model",
                    "provider",
                    "total_tokens",
                    "prompt_tokens",
                    "completion_tokens",
                    "cost",
                    "latency_ms",
                    "cached",
                    "saved_cost",
                    "pii_type",
                    "pii_field",
                    "action_taken",
                    "repeat_count",
                    "limit",
                    "spent",
                    "action",
                    "shadow_status",
                    "local_model",
                    "local_latency_ms",
                    "local_tokens",
                    "cost_saved",
                    "similarity_score",
                    "match_type",
                    "original_model",
                    "routing_success",
                    "complexity_score",
                    "semantic_complexity",
                    "original_cloud_model",
                    "estimated_cloud_cost",
                    "routing_reason",
                    "reason",
                    "message",
                    "matched_rule",
                    "blocked_model",
                    "blocked_provider",
                    "trigger",
                    "count",
                    "threshold",
                    "webhook_fired",
                    "webhook_url",
                    "agent_id",
                ):
                    val = getattr(event, attr, None)
                    if val is not None:
                        event_data[attr] = val
                try:
                    await broadcast_event(event_data)
                except Exception:
                    pass
        except ImportError:
            pass
        except Exception:
            logger.debug("Failed to broadcast events", exc_info=True)
